### PR TITLE
Added the support for setting rate limit for both kinds of stores

### PR DESCRIPTION
**Pull request by NikanV**
As i mentioned in this issue : #6

### CODE REVIEW

**Comment by Nebula1213** [comment]
Can you explain more what ResetTime is? To me it just looks like you replaced rate with ResetTime and did not actually and any new functionality.

**Comment by NikanV** [comment]
Of course, in the previous version you used `rate` for both setting time limit for banning users and also resetting the time limit for banning users. In this version you have the previous `rate` that only sets the time limit for banning users and you can also set the `resetTime` which is the time for unbanning the users and i think is much more practical than using only `rate` for both. 

You can see one of its usages in this [link](https://github.com/NikanV/WP-Hw1/blob/main/gateway-server/main.go)

**Comment by Nebulizer1213** [comment]
"In this version you have the previous rate that only sets the time limit for banning users" In your implementation the rate variable is not being used at all. I looked over the code and I don't think it is doing what you are intending it to do or I might just not fully understand what you are trying to do. Most people would never need the rate and reset time to be different. Adding this feature would over complicate the default stores. The default stores are meant for basic use cases. Feel free to make a third party store for the public to use.

**Comment by Nebula1213** [comment]
"In this version you have the previous rate that only sets the time limit for banning users" In your implementation the rate variable is not being used at all. I looked over the code and I don't think it is doing what you are intending it to do or I might just not fully understand what you are trying to do. Most people would never need the rate and reset time to be different. Adding this feature would over complicate the default stores. The default stores are meant for basic use cases. Feel free to make a third party store for the public to use.

**Pull request closed without merging**
